Add BQ table check job
DFE-Digital/check-childrens-barred-list pull request #253
Opened 2024-02-15 14:25 UTC by steventux

### Context

The data insights team have asked if we can add a check to our services to verify the data that we’re holding in BigQuery. The check periodically sends table row counts that can be checked against the big query data and runs as a scheduled job.

### Changes proposed in this pull request

Add dfe-analytics config and schedule appropriate job to check tables.

### Guidance to review

### Link to Trello card

https://trello.com/c/fVu2pkoU/1820-add-bigquery-table-check

### Checklist

- [x] Attach to Trello card
- [x] Rebased main
- [x] Cleaned commit history
- [ ] Tested by running locally

2024-02-15 14:26 UTC, steventux commented
![](https://github.trello.services/images/mini-trello-icon.png) [Add BigQuery table check](https://trello.com/c/fVu2pkoU/1820-add-bigquery-table-check)

2024-02-16 11:22 UTC, gpeng requested changes

2024-02-16 11:22 UTC, gpeng commented on config/clock.rb
> +  every(30.minutes, "DfE::Analytics::EntityTableCheckJob.set(queue: 'analytics').perform_later")
The data insights team are suggesting once a day. I don't think we need to send it this often.

2024-02-20 10:53 UTC, gpeng approved these changes

2024-02-20 14:42 UTC, merged