[99] BigQuery integration
DFE-Digital/check-childrens-barred-list pull request #84
Opened 2023-08-09 15:01 UTC by AbigailMcP

### Context

We want to be able to track the usage of our service. Using BigQuery is an established pattern across DfE.

It needs to be explicitly in development as you need a key from the Google Cloud console in order to use it.

Follow the instructions in the README for more detail.

### Changes proposed in this pull request

Add event tracking with BiqQuery / dfe-analytics
Remove the active_storage tables that were generated automatically and aren't needed for this project

### Link to Trello card

https://trello.com/c/d4lqiMQJ/99-add-bigquery-integration

### Checklist

- [x] Attach to Trello card
- [x] Rebased main
- [x] Cleaned commit history
- [x] Tested by running locally

2023-08-09 16:02 UTC, AbigailMcP commented
![](https://github.trello.services/images/mini-trello-icon.png) [Add BigQuery integration](https://trello.com/c/d4lqiMQJ/99-add-bigquery-integration)

2023-08-14 11:38 UTC, AbigailMcP commented on terraform/aks/variables.tf
> +      BIGQUERY_PROJECT_ID = "teaching-qualifications",
I think these could also go in `terraform/aks/config/app_config.yml` 🤷‍♀️

2023-08-15 09:58 UTC, steventux approved these changes
:rocket:

2023-08-15 09:59 UTC, gpeng requested changes

2023-08-15 10:40 UTC, AbigailMcP commented on config/analytics.yml
> +  :active_storage_blobs:
gone! 4b65a8ee3068fcf01e4fb8cb0db4c46cd6f9b16c

2023-08-16 13:11 UTC, gpeng approved these changes

2023-08-16 14:07 UTC, merged